books/urls.py
from django.urls import path
from books.views import BooksView, BookDetail, CreateBook, UpdateBook

app_name="books"

urlpatterns = [
  path("", BooksView.as_view(), name="books"),
  path("<int:pk>", BookDetail.as_view(), name="book"),
  path("<int:pk>/update", UpdateBook.as_view(), name="update"),
  path("create", CreateBook.as_view(), name="create"),
]

config/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("movies/", include("movies.urls", namespace="movies")),
    path("books/", include("books.urls", namespace="books")),
    path("favs/", include("favs.urls", namespace="favs")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("genres/", include("categories.urls", namespace="genres")),
    path("people/", include("people.urls", namespace="people")),
    path("users/", include("users.urls", namespace="users")),
    path(os.environ.get("DJANGO_ADMIN", "admin/"), admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from core.views import resolve_home, resolve_search, CategoryDetail

app_name="core"

urlpatterns = [
  path("", resolve_home, name="home"),
  path("search/", resolve_search, name="search"),
  path("search/<int:pk>/", CategoryDetail.as_view(), name="category")
]

favs/urls.py
from django.urls import path
from .views import toggle_favs ,SeeFavsView

app_name="favs"

urlpatterns=[
  path("add/<int:pk>",toggle_favs,name="toggle-favs" ),
    path("my_fav_list/", SeeFavsView.as_view(), name="favs-list"),

]

users/urls.py
from django.urls import path
from users.views import logout_view, LoginView, SignUpView, UserProfileView, UpdateProfileView, UpdatePasswordView

app_name="people"

urlpatterns = [
  path("logout", logout_view, name="logout"),
  path("login", LoginView.as_view(), name="login"),
  path("signup", SignUpView.as_view(), name="signup"),
  path("<int:pk>", UserProfileView.as_view(), name="profile"),
  path("update-profile/", UpdateProfileView.as_view(), name="update"),
  path("update-passwod/", UpdatePasswordView.as_view(), name="password"),
  
]

templates/partials/book_boxes.html
<div class="shadow-xl  rounded-xl px-4 py-4">
  <div class="text-lg font-bold mb-8 ">Books</div>
  <div class="flex item-center flex-wrap">
  {% for book in books %}
  <div class="w-1/5">
    {% include "mixins/book.html" with book=book %}
  </div>
  {% endfor %}
  </div>
</div>

templates/partials/comments.html
<div>
  <div class="font-bold mt-4">
    <span>Reveiws</span>
    <span class="text-gray-500 text-sm">({{model.total_reviews}})</span>
  </div>

  {% for review in model.reviews.all %}
  <div class="border-b my-2 mx-2">
    <div class="flex item-center">
      <div>          
        <span class="font-bold text-sm ">{{review.created_by.first_name}}</span>
        <span class="text-sm"><i class="fas fa-star text-red-500 text-xs mr-1"></i>{{review.rating}}</span>
      </div>
      <span class="text-sm text-gray-500 ml-4">{{review.created_at|date:"F Y"}}</span>
    </div>
    <div class="ml-2 mb-2 ">
      <span class="text-sm ">{{review.text}}</span>
    </div>
  </div>
  {% endfor %}

  <div class="font-bold mt-4">
    {% if user.is_authenticated %}
    <span>Write a review</span>
    <form action="{% url 'reviews:create' model.pk %}?type={{type}}" method="POST">
      {% csrf_token %}
      {% for field in form %}
        <div class="mb-2 ">
            <label class="block text-gray-700 font-bold text-sm" for="{{field.auto_id}}">{{field.label}}</label>
            <div class="appearance-none border rounded w-full border-red-500 text-gray-700 leading-loose focus:outline-none">
              {{field}}
            </div>
        </div>
      {% endfor %}
      <button class="block mx-auto font-bold text-blue-500 mb-4">Submit</button>
    </form>

    {% endif %}
  </div>

</div>

templates/partials/footer.html
<footer class="mt-8">
  &copy; GoodPedia
</footer>

templates/partials/header.html
  <header class="container fixed inset-x-0 bg-white top-0 max-w-full flex item-center justify-between  py-4  px-24 border-b border-gray-400">
    <div class="flex item-center  py-1">
      <a class="" href="{% url 'core:home' %}">Home</a>
      
    </div>

    <div class="flex item-center py-1">
        <a class="mr-5 text-gray-500 px-2  hover:text-red-500 	" href="{% url 'core:search' %}">Search</a>
      {% if user.is_authenticated %}
      <a class="mr-5 text-gray-500 px-2  hover:text-red-500 	" href="{% url 'favs:favs-list' %}">My Favs</a>        
      <a class="mr-5 text-gray-500 px-2  hover:text-red-500 	" href="{% url 'users:profile' user.pk %}">My Profile</a>
      <a class="mr-5 text-gray-500 px-2  hover:text-red-500 	" href="{% url 'users:logout' %}">Log Out</a>
      {% else %}
        <a class="mr-5 text-gray-500 px-2 hover:text-red-500 	" href="{% url 'users:login' %}">Log In</a>
        <a class="mr-5 text-gray-700 px-2  border rounded-lg border-gray-600 " href="{% url 'users:signup' %}">Sign Up</a>
      {% endif %}
    </div>

  </header>

templates/partials/movie_boxes.html
<div class="shadow-xl  rounded-xl px-4 py-4">
  <div class="text-lg font-bold mb-8 ">Movies</div>
  <div class="flex item-center flex-wrap">
  {% for movie in movies %}
  <div class="w-1/5">
    {% include "mixins/movie.html" with movie=movie %}
  </div>
  {% endfor %}
  </div>
</div>

templates/partials/person_boxes.html
<div class="shadow-xl  rounded-xl px-4 py-4">
  <div class="text-lg font-bold mb-8 ">People</div>
  <div class="flex item-center flex-wrap">
    {% for person in people %}
    <div class="w-1/5">
      {% include "mixins/person.html" with person=person %}
    </div>
    {% endfor %}
  </div>
</div>