books/urls.py
from django.urls import path
from books.views import BooksView, BookDetail, CreateBook, UpdateBook

app_name="books"

urlpatterns = [
  path("", BooksView.as_view(), name="books"),
  path("<int:pk>", BookDetail.as_view(), name="book"),
  path("<int:pk>/update", UpdateBook.as_view(), name="update"),
  path("create", CreateBook.as_view(), name="create"),
]

config/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("movies/", include("movies.urls", namespace="movies")),
    path("books/", include("books.urls", namespace="books")),
    path("favs/", include("favs.urls", namespace="favs")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("genres/", include("categories.urls", namespace="genres")),
    path("people/", include("people.urls", namespace="people")),
    path("users/", include("users.urls", namespace="users")),
    path(os.environ.get("DJANGO_ADMIN", "admin/"), admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from core.views import resolve_home, resolve_search, CategoryDetail

app_name="core"

urlpatterns = [
  path("", resolve_home, name="home"),
  path("search/", resolve_search, name="search"),
  path("search/<int:pk>/", CategoryDetail.as_view(), name="category")
]

favs/urls.py
from django.urls import path
from .views import toggle_favs ,SeeFavsView

app_name="favs"

urlpatterns=[
  path("add/<int:pk>",toggle_favs,name="toggle-favs" ),
    path("my_fav_list/", SeeFavsView.as_view(), name="favs-list"),

]

people/urls.py
from django.urls import path
from people.views import PeopleView, PersonDetail, CreatePerson, UpdatePerson

app_name="people"

urlpatterns = [
  path("", PeopleView.as_view(), name="people"),
  path("<int:pk>", PersonDetail.as_view(), name="person"),
  path("<int:pk>/update", UpdatePerson.as_view(), name="update"),
  path("create", CreatePerson.as_view(), name="create"),
]

books/models.py
from django.urls import reverse
from django.db import models
from core.models import CoreModel


class Book(CoreModel):

    """ Book Model """

    title = models.CharField(max_length=120)
    year = models.IntegerField()
    cover_image = models.ImageField(
        null=True, blank=True, upload_to='images/books/')
    rating = models.FloatField(default=0)
    category = models.ForeignKey(
        "categories.Category", on_delete=models.CASCADE, related_name="books")
    writer = models.ForeignKey(
        "people.Person", on_delete=models.CASCADE, related_name="books")

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("books:book", kwargs={"pk": self.pk})

    def total_rating(self):
        all_reviews = self.reviews.all()
        all_ratings = 0
        if len(all_reviews) > 0:
            for review in all_reviews:
                all_ratings += review.rating
            return round(all_ratings / len(all_reviews), 2)
        return 0

    def total_reviews(self):
        return self.reviews.count()

    class Meta:
        ordering = ["-year"]

books/views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from books.models import Book
from reviews.forms import CreateReviewForm


class BooksView(ListView):
  
  model = Book
  paginate_by = 10
  paginate_orphans = 5
  ordering = "-created_at"
  context_object_name = "books"

  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    context['page_title'] = "All Books"
    return context


class BookDetail(DetailView):
  model = Book
  context_object_name = 'book'
  form = CreateReviewForm
  def get_context_data(self,**kwargs):
    context=super().get_context_data(**kwargs)
    context['form'] = self.form
    return context



class CreateBook(CreateView):
  model = Book
  fields = (
    "title",
    "year",
    "cover_image",
    "category",
    "writer",
  )


class UpdateBook(UpdateView):
  model = Book
  fields = (
    "title",
    "year",
    "cover_image",
    "rating",
    "category",
    "writer",
  )

templates/books/book_detail.html
{% extends "base.html" %}
{% load is_book_on_favs %}

{% block page_title %}
{{book.title}}
{% endblock page_title %}

{% block content %}
  <div class="flex justify-center">

    <div class="container-md mx-auto w-2/5 flex flex-col border rounded-xl shadow-xl px-8 py-6 mt-4">
      <img src="{{book.cover_image.url}}" class="w-4/5 rounded place-self-center" alt="">
      <div class="flex  justify-between item-center ">
        <div class="text-2xl font-bold my-2">{{book.title}}</div>
          {% if user.is_authenticated %}
            {% is_book_on_favs book as on_favs_boolean %}
            {% if on_favs_boolean %}
              <div class="my-2"><a href="{% url 'favs:toggle-favs' book.pk %}?type=book&action=remove"> <i class="fas fa-heart text-red-500 mr-1 rounded-xl py-2 px-4 border-red-400 border-2"></i></a></div>
            {% else %}
              <div class="my-2"><a href="{% url 'favs:toggle-favs' book.pk %}?type=book&action=add"> <i class="fas fa-heart text-gray-500 mr-1 rounded-xl py-2 px-4 border-gray-400 border-2"></i></a></div>
            {% endif %}
          {% endif %}
      </div>
      <span class="text-sm mr-1" >{{book.year}} {{book.category}}</span>
      <span class="text-xs mr-1"> Rating <i class="fas fa-star text-red-500 text-xs mr-1"></i>{{book.total_rating}}</span>
      <span class="font-bold">Written by : <a class='text-blue-700 font-bold' href="{% url 'people:person' book.writer.pk %}">{{book.writer}}</a> </span>
      
      {% include 'partials/comments.html' with model=book type="book" %}
      {% include 'mixins/category.html' with model=book %}

      {% if user.is_authenticated %}
        <div class="bg-pink-500 hover:bg-pink-700 text-white font-bold rounded w-full mt-4 py-2 px-4 flex justify-center ">
          <a class="mx-auto " href="{% url 'books:update' book.pk %}">Edit Book</a>
        </div>
      {% endif %}

    </div>

  </div>

{% endblock content %}

templates/books/book_form.html
{% extends "base.html" %}

{% block page_title %}
  Modify Book
{% endblock page_title %}

{% block content %}

  {% include 'mixins/form.html' with form=form cta="Save" %}

{% endblock content %}

templates/books/book_list.html
{% extends "base.html" %}

{% block page_title %}
  Books
{% endblock page_title %}

{% block content %}
<div class="container mx-auto">
  <div class="pt-6 ">
    <div class="text-3xl mb-8">Books</div>
    <div class="flex item-center flex-wrap">
      {% for book in books %}
        <div class="w-1/5">
          {% include "mixins/book.html" with book=book %}
        </div>
      {% endfor %}
    </div>
  </div>
  <hr />
  <div>
    {% if page_obj.has_previous %}
          <a class="text-pink-600 mb-8"  href="?page={{page_obj.previous_page_number}}">Previous</a>
      {% endif %}

      Page {{page_obj.number}} of {{page_obj.paginator.num_pages}}

      {% if page_obj.has_next  %}
          <a class="text-pink-600 mb-8"  href="?page={{page_obj.next_page_number}}">Next</a>
      {% endif %}
  </div>
</div>
{% endblock content %}