config/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("movies/", include("movies.urls", namespace="movies")),
    path("books/", include("books.urls", namespace="books")),
    path("favs/", include("favs.urls", namespace="favs")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("genres/", include("categories.urls", namespace="genres")),
    path("people/", include("people.urls", namespace="people")),
    path("users/", include("users.urls", namespace="users")),
    path(os.environ.get("DJANGO_ADMIN", "admin/"), admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from core.views import resolve_home, resolve_search, CategoryDetail

app_name="core"

urlpatterns = [
  path("", resolve_home, name="home"),
  path("search/", resolve_search, name="search"),
  path("search/<int:pk>/", CategoryDetail.as_view(), name="category")
]

favs/urls.py
from django.urls import path
from .views import toggle_favs ,SeeFavsView

app_name="favs"

urlpatterns=[
  path("add/<int:pk>",toggle_favs,name="toggle-favs" ),
    path("my_fav_list/", SeeFavsView.as_view(), name="favs-list"),

]

movies/urls.py
from django.urls import path
from movies.views import MoviesView, MovieDetail, CreateMovie, UpdateMovie

app_name="movies"

urlpatterns = [
  path("", MoviesView.as_view(), name="movies"),
  path("<int:pk>", MovieDetail.as_view(), name="movie"),
  path("<int:pk>/update", UpdateMovie.as_view(), name="update"),
  path("create", CreateMovie.as_view(), name="create"),
]

people/urls.py
from django.urls import path
from people.views import PeopleView, PersonDetail, CreatePerson, UpdatePerson

app_name="people"

urlpatterns = [
  path("", PeopleView.as_view(), name="people"),
  path("<int:pk>", PersonDetail.as_view(), name="person"),
  path("<int:pk>/update", UpdatePerson.as_view(), name="update"),
  path("create", CreatePerson.as_view(), name="create"),
]

movies/models.py
from django.urls import reverse
from django.db import models
from core.models import CoreModel


class Movie(CoreModel):

    """ Movie Model """

    title = models.CharField(max_length=120)
    year = models.IntegerField()
    cover_image = models.ImageField(
        null=True, blank=True, upload_to='images/movies/')
    rating = models.IntegerField(default=0)
    category = models.ForeignKey(
        "categories.Category", on_delete=models.CASCADE, related_name="movies")
    director = models.ForeignKey(
        "people.Person", on_delete=models.CASCADE, related_name="movies")
    cast = models.ManyToManyField("people.Person", related_name="c_movies")

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("movies:movie", kwargs={"pk": self.pk})

    def total_rating(self):
        all_reviews = self.reviews.all()
        all_ratings = 0
        if len(all_reviews) > 0:
            for review in all_reviews:
                all_ratings += review.rating
            return round(all_ratings / len(all_reviews), 2)
        return 0

    def total_reviews(self):
        return self.reviews.count()

    class Meta:
        ordering = ["-year"]

movies/views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from movies.models import Movie
from reviews.forms import CreateReviewForm


class MoviesView(ListView):

    model = Movie
    paginate_by = 10
    paginate_orphans = 5
    ordering = "-created_at"
    context_object_name = "movies"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = "All Movies"
        return context


class MovieDetail(DetailView):
    model = Movie
    context_object_name = 'movie'
    form = CreateReviewForm
    def get_context_data(self,**kwargs):
      context=super().get_context_data(**kwargs)
      context['form'] = self.form
      return context


class CreateMovie(CreateView):
    model = Movie
    fields = (
        "title",
        "year",
        "cover_image",
        "category",
        "director",
        "cast",
    )


class UpdateMovie(UpdateView):
    model = Movie
    fields = (
        "title",
        "year",
        "cover_image",
        "rating",
        "category",
        "director",
        "cast",
    )

templates/movies/movie_detail.html
{% extends "base.html" %}
{% load is_movie_on_favs %}

{% block page_title %}
{{movie.title}}
{% endblock page_title %}

{% block content %}
  <div class="flex justify-center">

    <div class="container-md mx-auto w-2/5 flex flex-col border rounded-xl shadow-xl px-8 py-6 mt-4">
      <img src="{{movie.cover_image.url}}" class="w-4/5 rounded place-self-center	" alt="">
      <div class="flex  justify-between item-center ">
        <div class="text-2xl font-bold my-2">{{movie.title}}</div>
        {% if user.is_authenticated %}
          {% is_movie_on_favs movie as on_favs_boolean %}
          {% if on_favs_boolean %}
            <div class="my-2"><a href="{% url 'favs:toggle-favs' movie.pk %}?type=movie&action=remove"> <i class="fas fa-heart text-red-500 mr-1 rounded-xl py-2 px-4 border-red-400 border-2"></i></a></div>
          {% else %}
            <div class="my-2"><a href="{% url 'favs:toggle-favs' movie.pk %}?type=movie&action=add"> <i class="fas fa-heart text-gray-500 mr-1 rounded-xl py-2 px-4 border-gray-400 border-2"></i></a></div>
          {% endif %}
        {% endif %}
      </div>
      <span class="text-sm mr-1" >{{movie.year}} {{movie.category}}</span>
      <span class="text-xs mr-1"> Rating <i class="fas fa-star text-red-500 text-xs mr-1"></i>{{movie.total_rating}}</span>

      <div>
        <div class="font-medium border-t my-2">
          <span class="font-bold">Directed by </span>
          <a class='text-blue-700 font-bold' href="{% url 'people:person' movie.director.pk %}">{{movie.director}}</a></div>
        <div>
          <span class="font-bold">Casting</span>
          <div class="flex flex-col">
            {% for cast in movie.cast.all %}
            <span class="font-medium"><a class='text-blue-600' href="{% url 'people:person' cast.pk %}">{{cast}}</a></span> 
            {% endfor %}
          </div>
        </div>
      </div>

      {% include 'partials/comments.html' with model=movie form=form type="movie" %}
      {% include 'mixins/category.html' with model=movie %}

      {% if user.is_authenticated %}
      <div class="bg-pink-500 hover:bg-pink-700 text-white font-bold rounded w-full mt-4 py-2 px-4 flex justify-center ">
        <a class="mx-auto " href="{% url 'movies:update' movie.pk %}">Edit Movie</a>
      </div>
      {% endif %}


    </div>


  </div>

{% endblock content %}

templates/movies/movie_form.html
{% extends "base.html" %}

{% block page_title %}
  Movie
{% endblock page_title %}

{% block content %}

  {% include 'mixins/form.html' with form=form cta="Save" %}

{% endblock content %}

templates/movies/movie_list.html
{% extends "base.html" %}

{% block page_title %}
  Movies
{% endblock page_title %}

{% block content %}
<div class="container mx-auto">
  <div class="pt-6 ">
    <div class="text-3xl mb-8">Movies</div>
    <div class="flex item-center flex-wrap">
    {% for movie in movies %}
      <div class="w-1/5">
        {% include "mixins/movie.html" with movie=movie %}
      </div>
    {% endfor %}
    </div>
  </div>
<hr />

<div>
  {% if page_obj.has_previous %}
        <a class="text-pink-600 mb-8"  href="?page={{page_obj.previous_page_number}}">Previous</a>
    {% endif %}

    Page {{page_obj.number}} of {{page_obj.paginator.num_pages}}

    {% if page_obj.has_next  %}
        <a class="text-pink-600 mb-8"  href="?page={{page_obj.next_page_number}}">Next</a>
    {% endif %}
</div>

</div>

{% endblock content %}