books/urls.py
from django.urls import path
from books.views import BooksView, BookDetail, CreateBook, UpdateBook

app_name="books"

urlpatterns = [
  path("", BooksView.as_view(), name="books"),
  path("<int:pk>", BookDetail.as_view(), name="book"),
  path("<int:pk>/update", UpdateBook.as_view(), name="update"),
  path("create", CreateBook.as_view(), name="create"),
]

config/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("movies/", include("movies.urls", namespace="movies")),
    path("books/", include("books.urls", namespace="books")),
    path("favs/", include("favs.urls", namespace="favs")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("genres/", include("categories.urls", namespace="genres")),
    path("people/", include("people.urls", namespace="people")),
    path("users/", include("users.urls", namespace="users")),
    path(os.environ.get("DJANGO_ADMIN", "admin/"), admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from core.views import resolve_home, resolve_search, CategoryDetail

app_name="core"

urlpatterns = [
  path("", resolve_home, name="home"),
  path("search/", resolve_search, name="search"),
  path("search/<int:pk>/", CategoryDetail.as_view(), name="category")
]

movies/urls.py
from django.urls import path
from movies.views import MoviesView, MovieDetail, CreateMovie, UpdateMovie

app_name="movies"

urlpatterns = [
  path("", MoviesView.as_view(), name="movies"),
  path("<int:pk>", MovieDetail.as_view(), name="movie"),
  path("<int:pk>/update", UpdateMovie.as_view(), name="update"),
  path("create", CreateMovie.as_view(), name="create"),
]

users/urls.py
from django.urls import path
from users.views import logout_view, LoginView, SignUpView, UserProfileView, UpdateProfileView, UpdatePasswordView

app_name="people"

urlpatterns = [
  path("logout", logout_view, name="logout"),
  path("login", LoginView.as_view(), name="login"),
  path("signup", SignUpView.as_view(), name="signup"),
  path("<int:pk>", UserProfileView.as_view(), name="profile"),
  path("update-profile/", UpdateProfileView.as_view(), name="update"),
  path("update-passwod/", UpdatePasswordView.as_view(), name="password"),
  
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
  <link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">
  <style>
		input, select, textarea {
			width: 100%;
			padding-left: 0.75rem;
			padding-right: 0.75rem;
			padding-top: 0.5rem;
			padding-bottom: 0.5rem;
    }
	</style>
  <title>{% block page_title %}{% endblock page_title %} | GoodPedia</title>
</head>
<body class="text-gray-800 mt-16">
  {% include 'partials/header.html' %}
 
  {% block content %}
  {% endblock content %}

  {% include 'partials/footer.html' %}
</body>
</html>

templates/home.html
{% extends "base.html" %}

{% block page_title %}
  Home
{% endblock page_title %}

{% block content %}
<div class="container mx-auto">
  <div class="pt-6 ">
	<div class="text-3xl mb-8">Movies <a class="text-sm text-red-500" href="{% url 'movies:create' %}">[create]</a></div>
  <div class="flex item-center flex-wrap">
  {% for movie in movies %}
    <div class="w-1/5">
      {% include "mixins/movie.html" with movie=movie %}
    </div>
	{% endfor %}
  </div>

	<a class="text-pink-600 mb-8" href="{% url 'movies:movies' %}">See all movies &rarr;</a>
	<hr />
</div>

<div class="pt-6">
	<div class="text-3xl mb-8">Books <a class="text-sm text-red-500" href="{% url 'books:create' %}">[create]</a></div>
  <div class="flex item-center flex-wrap">
    {% for book in books %}
      <div class="w-1/5">
        {% include "mixins/book.html" with book=book %}
      </div>
    {% endfor %}
  </div>

	<a class="text-pink-600 mb-8" href="{% url 'books:books' %}">See all books &rarr;</a>
	<hr />
</div>

<div class="pt-6">
	<div class="text-3xl mb-8">People <a class="text-sm text-red-500" href="{% url 'people:create' %}">[create]</a></div>
  <div class="flex item-center flex-wrap">
    {% for person in people %}
      <div class="w-1/5">
      {% include "mixins/person.html" with person=person %}
      </div>
    {% endfor %}
  </div>

	<a class="text-pink-600 mb-8" href="{% url 'people:people' %}">See all people &rarr;</a>
	<hr />
<div>
{% endblock content %}

templates/search.html
{% extends "base.html" %}

{% block page_title %}
  Search
{% endblock page_title %}


{% block content %}
<div class="container mx-auto">

  <form class="flex justify-center pt-4	" method="GET" action="{% url 'core:search' %}" > 
    <input class="border rounede w-3/4 mr-4 shadow focus:outline-none " type="text" placeholder="Search Movie, Book or Person" name="name" value="{{name}}"/>
    <button class="bg-pink-500 hover:bg-pink-600 focus:outline-none text-white font-bold rounded w-36 mt-2 py-2 px-4">Search</button>
  </form>

  {% if name == "Anything" %}
    {% include 'mixins/categories_list.html' %}
  {% endif %}

  <div>
    <div class="text-xl font-bold my-8">Searching by "{{name}}"</div>

    {% if movies.count > 0 %}
      {% include 'partials/movie_boxes.html' with movies=movies %}
    {% endif %}
    {% if books.count > 0 %}
      {% include 'partials/book_boxes.html' %}
    {% endif %}
    {% if people.count > 0 %}
      {% include 'partials/person_boxes.html' %}


    {% endif %}
  </div>

</div>
{% endblock content %}